services:
  certificate-generator:
    build: .
    volumes:
      - ./pdfs:/app/pdfs
      - ./workshop_info.txt:/app/workshop_info.txt
      - ./certificate.tex:/app/certificate.tex
      - ./logos:/app/logos
    working_dir: /app
    # To run: docker-compose run --rm certificate-generator
    # Or to rebuild and run: docker-compose up --build
